### ISSUE TITLE
Issue since few day : Malformed Json

### ISSUE THREAD

**Issue by Poloche9x7** [beavis69/tv_grab_fr_telerama#36]
Hi, since few days, script can't grab on telerama... I have an error with json malformed.
Can you explain me why please ?

> Getting EPG Telerama...
getting listings: #malformed json on https://api.telerama.fr/v3/programmes/grille?appareil=android_tablette&date=2021-09-30&heure_debut=00:00&heure_fin=23:59&id_chaines=111,112,115,118,119,121,128,145,147,185,191,192,195,197,205,225,226,229,234,241,243,282,283,284,285,287,293,299,300,321,325,344&nb_par_page=3200&page=1&api_cle=apitel-g4aatlgif6qzf&api_signature=c0c89829877d630019319f6313f56fe4ecea74ac : 200 OK
Getting EPG Webgrab...

**Comment by beavis69** [comment]
Hi,
Which version are you using ?

tv_grab_fr_telerama --version
XMLTV module version 0.6.1
This program version $Id: tv_grab_fr_telerama,v 2.8 2021/05/29 11:30:00 zubrick Exp $

Please ensure you're using last version : 2.8 2021/05/29 11:30:00

**Comment by Poloche9x7** [comment]
> hts@raspberrypi:~/xmlepg/telerama$ ./tv_grab_fr --version
XMLTV module version 0.6.1
This program version $Id: tv_grab_fr_telerama,v 2.8 2021/05/29 11:30:00 zubrick Exp $
hts@raspberrypi:~/xmlepg/telerama$ ./tv_grab_fr --config-file /home/hts/xmlepg/telerama/telerama.conf --days 10 --output /home/hts/xmlepg/telerama.xml
getting listings: malformed json on https://api.telerama.fr/v3/programmes/grille?appareil=android_tablette&date=2021-09-30&heure_debut=00:00&heure_fin=23:59&id_chaines=1403,10,5,111,1960,481,924,321,445,34,33,30,32,1563,35,36,1399,287,285,283,401,284,282,226&nb_par_page=3200&page=1&api_cle=apitel-g4aatlgif6qzf&api_signature=5e931ca56e109918b57b7859e0c1da46832a82c6
200 OK : Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 23072768 bytes) in /var/www/telerama-api/vendor/symfony/cache/Traits/RedisTrait.php

I have already the latest version...

**Comment by beavis69** [comment]
This is an issue on telerama servers api (php memory_limit), not on our side.

You can try to lower the number of channels in each api request to lower memory usage.

Try editing line 434 :

**Comment by beavis69** [comment]
`my $group_size = 24;`
to
`my $group_size = 20;`
or less.

**Comment by beavis69** [comment]
less channels in one call, means less memory on server side, but also means more calls / more time to grab tv programs...

**Comment by Poloche9x7** [comment]
Grabber process finished in 170 seconds for 118 chans, 61 api calls : 60 api_grille, 1 api_init, 0 cached api_casting

With group size = 20

It's works fine !

**Comment by beavis69** [comment]
This append randomly only with channels that have a lot of short time programs per day like gulli or kids channels.

with group_size = 24 , i've seen the problem only 1 or 2 times per month.

**Comment by Poloche9x7** [comment]
Can you send me your email in private, i'm french user, i have other questions, but it's better for me to speak in french with you :)

**Comment by beavis69** [comment]
Yes let's switch to french.

**Comment by Poloche9x7** [comment]
OK, depuis quelques temps, j'ai remarqué que télérama avait tous les EPG a jour sur cette adresse : https://television.telerama.fr/tele/grille?ce-soir

Or, sur l'adresse ou l'on grab il n'y a pas les meme EPG...

Exemple pour TF1 : 
--> https://television.telerama.fr/tele/grille?jour=7&heure=21 -- les EPG sont présents jusqu'au 13.10
--> https://television.telerama.fr/tele/chaine-tv/tf1,192.php?date=2021-10-05 -- a partir du 10.05, il n'y a pas d'epg...

En fait, la grille des programme est complétée proprement, alors que les adresse des chaines individuelles ne sont pas à jour.

N'y a til pas une solution envisageable de grabber a partir de la grille ?

Merci

**Comment by beavis69** [comment]
Je comprends pas trop la question.

On utilise aucune des urls que tu donnes, on utilise l'api, la même qui est utilisée par les applis android/ios.

Le but ce serait quoi ? d'avoir plus de jours ?  T'as essayyé un --days 13 ?

**Comment by beavis69** [comment]
Tu peux changer my $max_days = 11; et le passer à 13 si tu veux faire des essais, mais en dehors des chaines de la TNT il est probable que tu n'ai rien au dela de 7 jours.

**Comment by Poloche9x7** [comment]
Par exemple lorsque je grab avec le script, pour c+ avec le paramètre days = 10, il me dit : 
Aucun programme pour la chaîne 34 Canal+ le 2021-10-06

Or, si on se connecte sur le site de télarama et que l'on regarde la grille des programme à cette adresse : https://television.telerama.fr/tele/grille?jour=6&heure=21
Il y a bien les programmes de disponibles pour la chaine canal+ pour le 06.10 et ce jusqu'au jour 13.10 inclus.

Donc comment cela se fait que l'api ne les voit pas ?

**Comment by beavis69** [comment]
Le site ne semble pas utiliser l'api, il ne doit probablement pas avoir la même source de données pour l'affichage en grille.

Par contre, si tu testes l'appli sous android ou ios qui utilise l'api, tu verra que l'appli télérama n'a pas les données non plus.
Je pense également que la vue par chaine : https://television.telerama.fr/tele/chaine-tv/tf1,192.php?date=2021-10-05, elle utilise l'api donc a moins de données.

On pourrait en théorie récuperer les données sur le site (vue grille) et gagner des jours supplémentaires, mais il faut écrire completement le code pour cela, ce n'est pas du tout le même format de données.

Il faudrait beaucoup plus d'appels : les journées sont découpées en tranche de 3 heures, alors qu'avec l'api on récupere une journée complète en 1 appel pour 24 chaines.

Sur la grille du site, il y'a vraiment beaucoup moins d'infos détaillées que dans le json de l'api, et en plus il y a vraiment beaucoup moins de chaines.

Bref beaucoup de boulot alors que l'api fournit déja entre 7 jours et 11 jours de programmes suivant les chaines.

**Comment by zubrick** [comment]
Salut,

Je suis assez d'accord avec @beavis69 
Le tv_grab_fr originel utilisait le site web et parsait les pages pour récupérer les données. 
Tous les 2-3 mois, c'était complètement cassé parce qu'ils avaient changé quelque chose sur leur site.
Ca représentait un travail énorme à chaque fois, et le temps qu'on remarque et que je corrige, y'avait plus de programme pendant plusieurs jours.
C'est là que j'ai eu l'idée de faire cette version qui récupérait les données comme un téléphone.

Je n'utilise plus le grabber depuis un moment, mais de ce que je remarque des tickets ouverts, peut-être que de temps en temps c'est un peu cassé et qu'il n'y a pas beaucoup de jours d'avance, mais c'est tellement plus stable.
Et généralement ils corrigent parce qu'ils tiennent à garder leurs apps fonctionnelles et qu'ils ne peuvent pas se permettre de changer l'API si facilement.

**Comment by beavis69** [comment]
On va attendre quelque jours, l'api semble avoir des problèmes actuellement y'a rien sur les applis mobile à partir du 10/05

@zubrick : si tu peux me passer propriétaire du repo, ça me permettra de faire des templates pour les issues, histoire que les gens donnent certaines infos (version / commande utilisée, ...) à l'ouverture d'un ticket

**Comment by pdeliot** [comment]
C'est malheureusement souvent le cas chez Télérama.
Il manque parfois l'info sur plusieurs chaines (genre le groupe TF1 complet) , ou rien à moins de 24 heures...

Mais là le grabber n'y peut rien :-(

**Comment by Poloche9x7** [comment]
Merci pour vos réponses. Mais il est vrai que télérama fait de plus en plus n'importe quoi. Je me demande si c'est pas le stagiaire d'été qui a été embauché ^^
J'ai maintenant une fois sur 2 un progblème de memory (meme avec une valeur inférieur a 24 dans le script), et hier j'ai eu carrement une erreur 500

Getting EPG Telerama...
getting listings: Erreur 500 Status read failed: Connection reset by peer, url: https://api.telerama.fr/v3/programmes/grille?appareil=android_tablette&date=2021-10-01&heure_debut=00:00&heure_fin=23:59&id_chaines=79,80,87,88,94,98,100,101,102,103,104,105,106,108,110,111,112,115,116,118&nb_par_page=3200&page=1&api_cle=apitel-g4aatlgif6qzf&api_signature=1caa4c72c4fa6fa80af3ccde5ffaff1bca6c3e59 , retrying...
Erreur 500 Status read failed: Connection reset by peer, url: https://api.telerama.fr/v3/programmes/grille?appareil=android_tablette&date=2021-10-01&heure_debut=00:00&heure_fin=23:59&id_chaines=79,80,87,88,94,98,100,101,102,103,104,105,106,108,110,111,112,115,116,118&nb_par_page=3200&page=1&api_cle=apitel-g4aatlgif6qzf&api_signature=1caa4c72c4fa6fa80af3ccde5ffaff1bca6c3e59

Finalement nous sommes le 02.10 et je n'ai les programmes de mes chaines que jusqu'au 04.10. 

Très dommage de voir comment télérama nous empêche de grabber correctement comme avant

**Comment by micorpat** [comment]
Plus de contenu depuis ce 2 janvier 2022 (ou déjà depuis hier). Suis-je le seul concerné ?

**Comment by pdeliot** [comment]
Pas de problème particulier de mon côté.

Juste quelques manques habituels sur RFM et IDF1

**Comment by beavis69** [comment]
Je ne constate pas de problème non plus sur les chaines TNT/courantes mais certaines chaines n'ont plus de contenu.

```
Aucun programme pour la chaîne 10 Action le 2022-01-03
Aucun programme pour la chaîne 2037 Crime District le 2022-01-03
Aucun programme pour la chaîne 173 Seasons le 2022-01-03
Aucun programme pour la chaîne 1960 BET le 2022-01-03
Aucun programme pour la chaîne 5 AB1 le 2022-01-03
Aucun programme pour la chaîne 1073 BFM Business le 2022-01-03
Aucun programme pour la chaîne 140 EuroNews le 2022-01-03
Aucun programme pour la chaîne 529 France 24 le 2022-01-03
Aucun programme pour la chaîne 781 I24News le 2022-01-03
Aucun programme pour la chaîne 76 Eurosport 1 le 2022-01-03
Aucun programme pour la chaîne 439 Eurosport 2 le 2022-01-03
Aucun programme pour la chaîne 101 Multi-Sports 1 le 2022-01-03
Aucun programme pour la chaîne 102 Multi-Sports 2 le 2022-01-03
Aucun programme pour la chaîne 103 Multi-Sports 3 le 2022-01-03
Aucun programme pour la chaîne 104 Multi-Sports 4 le 2022-01-03
Aucun programme pour la chaîne 105 Multi-Sports 5 le 2022-01-03
Aucun programme pour la chaîne 106 Multi-Sports 6 le 2022-01-03
Aucun programme pour la chaîne 100 Foot+ 24/24 le 2022-01-03
#Aucun programme pour la chaîne 483 Baby TV le 2022-01-03
Aucun programme pour la chaîne 924 Boing le 2022-01-03
Aucun programme pour la chaîne 321 Boomerang le 2022-01-03
Aucun programme pour la chaîne 32 Canal J le 2022-01-03
Aucun programme pour la chaîne 36 Cartoon Network le 2022-01-03
Aucun programme pour la chaîne 58 Disney Channel le 2022-01-03
Aucun programme pour la chaîne 299 Disney Channel +1 le 2022-01-03
Aucun programme pour la chaîne 300 Disney Junior le 2022-01-03
Aucun programme pour la chaîne 1585 J-One le 2022-01-03
Aucun programme pour la chaîne 6 Mangas le 2022-01-03
Aucun programme pour la chaîne 1746 Nickelodéon 4 Teen le 2022-01-03
Aucun programme pour la chaîne 888 Nickelodéon Junior le 2022-01-03
Aucun programme pour la chaîne 473 Nickelodéon le 2022-01-03
Aucun programme pour la chaîne 344 Piwi+ le 2022-01-03
Aucun programme pour la chaîne 293 TéléToon+1 le 2022-01-03
Aucun programme pour la chaîne 197 TéléToon+ le 2022-01-03
Aucun programme pour la chaîne 229 TIJI le 2022-01-03
Aucun programme pour la chaîne 2040 Toonami le 2022-01-03
Aucun programme pour la chaîne 87 Game One le 2022-01-03
Aucun programme pour la chaîne 3163 culturebox le 2022-01-03
Aucun programme pour la chaîne 1357 Djazz le 2022-01-03
Aucun programme pour la chaîne 453 M6 Music le 2022-01-03
Aucun programme pour la chaîne 121 MCM le 2022-01-03
Aucun programme pour la chaîne 343 MCM Top le 2022-01-03
#Aucun programme pour la chaîne 265 Melody le 2022-01-03
Aucun programme pour la chaîne 128 MTV le 2022-01-03
Aucun programme pour la chaîne 605 NRJ Hits le 2022-01-03
Aucun programme pour la chaîne 241 RFM TV le 2022-01-03
Aucun programme pour la chaîne 325 Trace Urban le 2022-01-03
Aucun programme pour la chaîne 12 Animaux le 2022-01-03
Aucun programme pour la chaîne 400 Discovery Channel le 2022-01-03
Aucun programme pour la chaîne 1374 Discovery Science le 2022-01-03
Aucun programme pour la chaîne 719 Nat Geo Wild le 2022-01-03
Aucun programme pour la chaîne 402 Planète+ Aventure Expérience le 2022-01-03
Aucun programme pour la chaîne 1776 Trek le 2022-01-03
Aucun programme pour la chaîne 63 Science & Vie le 2022-01-03
Aucun programme pour la chaîne 1295 Golf+ le 2022-01-03
Aucun programme pour la chaîne 415 Nautical Channel le 2022-01-03
Aucun programme pour la chaîne 38 Chasse et Pêche le 2022-01-03
Aucun programme pour la chaîne 64 Equidia Live le 2022-01-03
#Aucun programme pour la chaîne 405 E! le 2022-01-03
Aucun programme pour la chaîne 254 ab 3 le 2022-01-03
Aucun programme pour la chaîne 701 idf1 le 2022-01-03
Aucun programme pour la chaîne 124 la chaîne météo le 2022-01-03
Aucun programme pour la chaîne 184 m6 boutique le 2022-01-03
Aucun programme pour la chaîne 183 rts deux le 2022-01-03
Aucun programme pour la chaîne 202 rts un le 2022-01-03
Aucun programme pour la chaîne 833 sundance le 2022-01-03

```

Du coup ça semble venir de chez eux, @micorpat tu peux vérifier sur l'appli android/ios si des programmes apparaissent pour les chaînes qu'il te manque.

**Comment by beavis69** [comment]
Je ferme, à priori plus de soucis.
